name: Unit tests

on:
  pull_request:
    branches: [master-2.0]

jobs:
  php-tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['8.0', '8.2', '8.3', '8.4', '8.5']
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run unit tests
        run: composer test
